name: music
description: A modern Flutter music player app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  just_audio: ^0.9.36
  audio_service: ^0.18.12
  permission_handler: ^11.3.1
  on_audio_query: ^2.9.0
  provider: ^6.1.1
  share_plus: ^9.0.0
  rxdart: ^0.28.0
  shared_preferences: ^2.2.2
  google_mobile_ads: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/images/muico.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/muico.png"
  min_sdk_android: 24
  web:
    generate: false
  macos:
    generate: false
  windows:
    generate: false
  linux:
    generate: false

flutter:
  uses-material-design: true
  assets:
    - assets/images/
